// 中文剧本 — 由 build.js 自动生成，请勿手动编辑
// 编辑 剧本/script_zh.md 后运行 node 剧本/build.js 重新生成
window.SCRIPT_ZH = {
  meta: {
    title: "厢间人",
    subtitle: "—— 献给所有困在车厢里的人",
    author: "",
    version: "0.1"
  },
  player: {
    stats: {
      哲学思辨: 3,
      逻辑推导: 4,
      缪斯女神: 2,
      灵魂叙事: 5,
      技术专家: 1,
      身强体壮: 2
    },
    hp: { current: 3, max: 3 },
    sanity: { current: 2, max: 3 }
  },
  itemTemplates: {
    "white_pill": {"usable":true,"consumeOnUse":true,"effect":{"sanity_restore":1},"name":"白色药片","description":"散发着青草气息的白色药片，闻起来让人感到心神安定。你不知道这是什么药，但你隐约明白了它的作用。","id":"white_pill"},
    "faded_thread": {"usable":true,"consumeOnUse":true,"effect":{"hp_restore":1},"name":"褪色的线头","description":"一根褪了色的红线头，大概是从某件旧西装上脱落的。你攥在手里的时候，会觉得安心——像是攥着某个人的袖口。","id":"faded_thread"}
  },
  scenes: {
  "开场": {
    background: "assets/bg_意识的诞生.png",
    music: "assets/灰雾_no-watermark.mp3",
    dialogue: [
      {"id":"wake_up","speaker":"旁白","text":"你醒了。\n\n不，准确地说——你正在醒来。你察觉到自己漂浮在某个边界上，左边是深海般的幽黑，如同黑洞，它正在旋转，吞噬着一切目光，连观测也不被允许。回过头，右边是某种灰白色牛乳般的空间。灰色的游鱼倏忽而来，又倏忽而逝。","next":"feeling_something_in_the_dark","choices":[],"bg":"assets/bg_意识的诞生.png","music":"assets/灰雾_no-watermark.mp3"},
      {"id":"feeling_something_in_the_dark","speaker":"旁白","text":"它们的触碰让你隐隐发痒。仿佛有什么东西在注视你，刺骨的寒冷开始在你的大脑皮层上爬动，发出哇哇孩童般的哭声，潮湿、黏稠的液体在空荡荡的头颅尖端凝聚，滴落，一丝臭氧和鱼腥味弥漫开来。还有一种电的味道。\n\n笑声在遥远的地方拉起了宇宙的辰星，一道名为人生的幕布即将就此被拼接而成。","choices":[{"text":"等等，电是什么味道？","next":"electric_feel","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"有点恐怖，我不想醒来。","next":"do_not_wake_up1","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"electric_feel","speaker":"旁白","text":"这个世界的医院每天会迎来5、6万的新生儿，大多数新生都伴随着手术室闪烁的灯光。门外，红灯变成绿灯；门内，电流之间的人露出欣慰的神情，有的护士会轻轻拍打婴儿的背，让哭不出的孩子发出声音。\n\n从人工电到生物电，于是有人说电流是蛋白质的味道。但那可能只是触电造成的。","choices":[{"text":"[灵魂叙事 简单:5] 我怎么听到了骰子的声音？","next":null,"check":{"stat":"灵魂叙事","difficulty":5},"success":"first_try_success","failure":"first_try_fail","effects":null,"inputName":false,"loop":false},{"text":"够了，别乱想了，我要醒来。","next":"first_look","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"do_not_wake_up1","speaker":"旁白","text":"黑暗的水散发出淡淡的铁锈味，这是因为有一把枪在你面前融化了。\n\n融化：并不是由于温度的增高，而是因为温度这一概念的消失。你预感到那尚未成形的听觉和视觉也在离你远去，你将再也看不见那数道身影，骰子还在滚动，但你已经听不见了。","choices":[{"text":"[灵魂叙事 简单:5] 这不是还有骰子吗？试一试","next":null,"check":{"stat":"灵魂叙事","difficulty":5},"success":"first_try_success","failure":"first_try_fail","effects":null,"inputName":false,"loop":false},{"text":"算了，就这样吧。","next":"do_not_wake_up2","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"first_try_success","speaker":"旁白","text":"对的！没错！骰子的声音！那令人着魔的声音！\n\n来吧，把生命再度交给骰子，从那湿润的黑暗中离开！","choices":[{"text":"我要醒来。","next":"first_look","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"到此为止，晚安。","next":"do_not_wake_up2","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"first_try_fail","speaker":"旁白","text":"没有什么骰子，错觉，光怪陆离的错觉。\n\n古旧的楼房墙面上攀满了爬山虎，在傍晚时分，城市的砖墙是最红的。在那叶片下的阴影里，有什么东西总是在凝望着你。然而你连这些也看不见了。","next":"do_not_wake_up2","choices":[]},
      {"id":"do_not_wake_up2","speaker":"旁白","text":"你蜷缩起来，如果你能控制你的四肢的话；\n你保持沉默，如果你还能控制气流的话；\n你睡着了，如果你还真的能有意识的话。\n\n那些灰色鱼儿又来了，柔软的灰，每一条鱼都是一个更庞大存在的手指，这千指之手攀附上了你不存在的身体，包裹着你，爱抚着你。\n\n然后从那人类漫长的历史中，你听见一声可怕的枪响。","next":null,"choices":[]},
      {"id":"first_look","speaker":"旁白","text":"你睁开眼。\n\n天花板很低。铆钉。金属板拼接的痕迹。一盏昏黄的灯在有节奏地微微晃动，光也跟着晃动——像是在水里。\n\n你听到一种低沉的、持续的嗡鸣声。不是耳鸣。是从墙壁里传来的。","next":"stand_up","choices":[],"bg":"assets/bg_车厢.png","music":"assets/轨道_no-watermark.mp3","volume":0.2},
      {"id":"stand_up","speaker":"旁白","text":"你试图站起来。腿是软的——不是因为虚弱，而是一种更根本的陌生感，好像这些肌肉不是你的，好像你还不确定自己和这具身体是什么关系。\n\n你扶着墙站住了。墙壁在震动。","choices":[{"text":"环顾四周。","next":"look_around","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"「有人吗？」","next":"call_out","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"look_around","speaker":"旁白","text":"这是一节火车车厢。\n\n但不太对劲。车厢的一侧有一扇窗户——长方形的，玻璃上蒙着一层灰，外面的东西看不清楚。你靠近窗户，用手擦了擦玻璃。\n\n灰在外面。\n\n玻璃内侧是干净的。那种灰——或者不是灰——均匀地贴在玻璃的另一面，像某种雾，但又比雾更……实在。它既流动又凝固，既像气体又像织物。你盯着它看了几秒，感到一种说不清的不安——不是因为它可怕，而是因为它让你想起了什么东西。你只是不记得是什么了。","next":"try_window","choices":[]},
      {"id":"try_window","speaker":"旁白","text":"你试着推了推窗户。锁死的。或者根本就没有锁——它看起来更像是被焊接封住的。你用手指敲了敲玻璃，声音闷闷的，像是敲在浸了水的木板上。\n\n窗户外面那个灰蒙蒙的东西没有反应。当然不会有反应。那又不是活的。\n\n……对吧？","next":"notice_no_door","choices":[]},
      {"id":"call_out","speaker":"你","text":"「有人吗——有没有人——」","next":"voice_responds","choices":[]},
      {"id":"voice_responds","speaker":"旁白","text":"你的声音在车厢里弹了两下就死了。这节车厢太小了——一个隔间大小——容不下回声。\n\n但然后你听到了什么。\n\n从墙壁的另一侧。不是回声。是一个人的声音。","next":"ansel_appears","choices":[]},
      {"id":"notice_no_door","speaker":"旁白","text":"你转身，目光扫过车厢的四壁。\n\n有窗的那面墙。\n\n对面是沙发——一张旧的、皮质开裂的双人沙发，扶手上有一个烟头烫过的痕迹。\n\n沙发旁边是一张小桌椅。桌上什么都没有。\n\n然后你意识到了一个问题。一个相当大的问题。\n\n这节车厢没有门。","choices":[{"text":"[逻辑推导 简单:7] 冷静地分析这个空间的结构。","next":null,"check":{"stat":"逻辑推导","difficulty":7},"success":"analyze_room_success","failure":"analyze_room_fail","effects":null,"inputName":false,"loop":false},{"text":"「没有门？」你大声说了出来。","next":"call_out","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"analyze_room_success","speaker":"逻辑推导","text":"等一下。一列火车上出现一个没有门的隔间，在物理上是不可能的。这意味着两种情况之一：\n\n一、门存在，只是被藏起来了。墙板可能有接缝，沙发可能挡住了一个推拉门。\n\n二、这个隔间不是为\"进入\"设计的。它是为\"困住\"而造的。\n\n两种可能性都不让人舒服。但第二种尤其不好。\n\n另外——这节车厢在火车中段。你刚才喊叫的时候，声音没有往走廊里传。这说明——墙体异常地厚。","next":"ansel_appears","choices":[]},
      {"id":"analyze_room_fail","speaker":"逻辑推导","text":"你试图清点这个空间的信息，但脑子里一片雾，什么都抓不住。你只知道：你在这里，没有门，窗外是灰的，墙在震。\n\n这四件事放一块儿，等于一个意思——你被关起来了。至于为什么、被谁、怎么做到的，你暂时没有力气去想。","next":"ansel_appears","choices":[]},
      {"id":"ansel_appears","speaker":"旁白","text":"墙壁的另一侧传来一阵窸窣声，然后是一个年轻女人的声音。带着一点不耐烦，但更多的是好奇。","next":"ansel_appears_voice","choices":[]},
      {"id":"ansel_appears_voice","speaker":"???","text":"「——听到了。听到了听到了。」\n\n「你是哪一站上来的？我怎么没在K城见过你？」","next":"ansel_appears_pause","choices":[]},
      {"id":"ansel_appears_pause","speaker":"旁白","text":"短暂的沉默。","next":"ansel_appears_question","choices":[]},
      {"id":"ansel_appears_question","speaker":"???","text":"「……等一下。你的声音是从哪传出来的？」","choices":[{"text":"「我不知道。我醒来就在这里。」","next":"ansel_confused","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"「先告诉我——这列火车是去哪的？」","next":"ansel_explain_train","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"[哲学思辨 困难:11] 「……也许我根本就没'上来'过。」","next":null,"check":{"stat":"哲学思辨","difficulty":11},"success":"ansel_philosophical","failure":"ansel_confused","effects":null,"inputName":false,"loop":false}]},
      {"id":"ansel_confused","speaker":"逻辑推导","text":"墙上传来手指敲击的声音。三下，指节，间隔均匀。她不是在随意地碰——她在测试墙的厚度，在确认你的位置。这说明你和她之间的障碍是物理的，不是心理的。她需要先理解这堵墙，才能决定怎么对待墙后的人。","next":"ansel_confused_voice","choices":[]},
      {"id":"ansel_confused_voice","speaker":"Ansel","text":"「嗯……这堵墙后面没有车厢啊。我这边是走廊。你那边——」","next":"ansel_confused_pause","choices":[]},
      {"id":"ansel_confused_pause","speaker":"旁白","text":"她顿了一下。","next":"ansel_confused_air","choices":[]},
      {"id":"ansel_confused_air","speaker":"Ansel","text":"「你那边按理说什么都不该有。这是两节车厢之间的连接处。理论上，你站的地方应该是……空气。」","next":"ansel_intro","choices":[]},
      {"id":"ansel_explain_train","speaker":"灵魂叙事","text":"她的声音稍微认真了一些。之前她的声调是上扬的——好奇，轻快，像在解一道有趣的谜。现在往下沉了半度。一个愿意跟你讲空海是什么的人，和一个愿意跟你讲铁轨是什么的人，是两种不同的认真。","next":"ansel_explain_train_voice","choices":[]},
      {"id":"ansel_explain_train_voice","speaker":"Ansel","text":"「哦——好的，对，你应该不太清楚——」\n\n「这趟列车是从K城开往A城的。诺斯塔吉亚号。人类在这个狗屁世界里仅存的两座城市之间，第一条铁轨。空海之后的第一条。你听懂了吗？空海——那个把世界吃掉的雾。已经三十多年了。」","next":"ansel_intro","choices":[]},
      {"id":"ansel_philosophical","speaker":"哲学思辨","text":"你脱口而出的话让你自己都吃了一惊。随即你意识到——这不是随便说的。\n\n如果你没有记忆，那你凭什么断定自己\"上了\"这列火车？也许你一开始就在墙上。也许你就是这节车厢。也许你是被某种东西——\n\n好了。打住。哲学思辨在这样的时候通常帮不了你。","next":"ansel_intro","choices":[]},
      {"id":"ansel_intro","speaker":"Ansel","text":"「总之——我叫Ansel。K城的人。你是……」","next":"ansel_intro_wait","choices":[]},
      {"id":"ansel_intro_wait","speaker":"旁白","text":"她等着你说名字。\n\n你没有说话。\n\n不是不想说。是你突然意识到——你不知道自己叫什么。\n\n这是种奇怪的感觉。一个词就在嘴边，一个这辈子你用过最多次的词，但你找不到它。它不在那里。","choices":[{"text":"「我……我不知道我叫什么。」","next":"forgot_name","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"努力回想。","next":"try_remember_name","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"随便编个名字。","next":"make_up_name","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"forgot_name","speaker":"缪斯女神","text":"长久的沉默。沉默是一种特殊的声音——它把周围的嗡鸣、呼吸、墙壁的震动都变成了乐器。在这段空白里，Ansel正在重新排列她脑子里关于你的所有碎片。安静是创造的前奏。她快要写出第一行了。","next":"forgot_name_voice","choices":[]},
      {"id":"forgot_name_voice","speaker":"Ansel","text":"「……你不记得自己的名字。」","next":"forgot_name_beat","choices":[]},
      {"id":"forgot_name_beat","speaker":"逻辑推导","text":"这不是问句。没有升调，没有疑问词，不需要你的确认。Ansel说\"你不记得自己的名字\"的方式，和她说\"这堵墙后面没有车厢\"是一样的——陈述事实。她已经在调整自己的认知模型了。","next":"forgot_name_ok","choices":[]},
      {"id":"forgot_name_ok","speaker":"Ansel","text":"「好吧。」","next":"forgot_name_soft","choices":[]},
      {"id":"forgot_name_soft","speaker":"灵魂叙事","text":"她的声音突然变得很轻，像是在对自己说话。不是对你说\"好吧\"，是对她自己。你听出来了——她不是在敷衍你，她是在消化。一个人消化一件不可能的事情时，声音会先塌下来。","next":"forgot_name_ok2","choices":[]},
      {"id":"forgot_name_ok2","speaker":"Ansel","text":"「好吧。」","next":"name_input","choices":[]},
      {"id":"try_remember_name","speaker":"旁白","text":"你闭上眼睛。\n\n名字。名字。\n\n你试图在空白的记忆里翻找，像在一个被清空的抽屉里摸索。手指碰到了一些碎片——\n\n一个人影。一扇窗户。夏天。汗湿的衬衫贴在背上的感觉。\n\n一个数字：503。\n\n没有名字。\n\n你睁开眼。","next":"name_input","choices":[]},
      {"id":"make_up_name","speaker":"缪斯女神","text":"名字。名字是诗歌的开头。是所有故事的第一个词。\n\n所以你为什么不给自己一个故事的开头呢？\n\n一个音节，一个笔划，一个能在这堵墙之间站住脚的词——那就是你了。至少现在是你。","next":"name_input","choices":[]},
      {"id":"name_input","speaker":"Ansel","text":"「没关系。慢慢想。如果实在想不起来——」","next":"name_input_beat","choices":[]},
      {"id":"name_input_beat","speaker":"逻辑推导","text":"她停了停。墙那边传来什么东西被翻开的声音——纸页的摩擦，然后是某种硬壳封面合上的脆响。也许是一本乘客名册。也许只是一本她自己带的笔记。无论如何，她正在用她能找到的工具来应对一个无法归类的情况。","next":"name_input_prompt","choices":[]},
      {"id":"name_input_prompt","speaker":"Ansel","text":"「你就告诉我，你想让我怎么叫你。」","choices":[{"text":"输入你的名字。","next":"ansel_questions","check":null,"success":null,"failure":null,"effects":{"inputName":true},"inputName":false,"loop":false}]},
      {"id":"ansel_questions","speaker":"Ansel","text":"「{playerName}。」","next":"ansel_questions_beat","choices":[]},
      {"id":"ansel_questions_beat","speaker":"灵魂叙事","text":"她念了一遍，像是在品尝这个词的重量。\n\n然后她沉默了几秒。当她再开口的时候，语调变了——不再是好奇，是某种谨慎。","next":"ansel_questions_probe","choices":[]},
      {"id":"ansel_questions_probe","speaker":"Ansel","text":"「你说你醒来就在里面。没有门。没有记忆。」","next":"ansel_questions_knock","choices":[]},
      {"id":"ansel_questions_knock","speaker":"逻辑推导","text":"她的手指在墙上敲了两下。和刚才不同——节奏慢了一倍，力度更轻。这不是试探墙的厚度，这是人在思考时的无意识动作。她正在把关于你的碎片拼成一幅图。但这幅图的边缘还缺了几块。她知道，她也知道你知道。","next":"ansel_questions_challenge","choices":[]},
      {"id":"ansel_questions_challenge","speaker":"Ansel","text":"「你怎么证明你不是自己走进去然后把门封上的？」","next":"ansel_questions_silence","choices":[]},
      {"id":"ansel_questions_silence","speaker":"旁白","text":"你没有回答。你没法回答。","next":"ansel_questions_anything","choices":[]},
      {"id":"ansel_questions_anything","speaker":"Ansel","text":"「你有任何东西吗？一个名字、一个地方、一个人——任何能证明你是谁的东西？」","next":"ansel_questions_silence2","choices":[]},
      {"id":"ansel_questions_silence2","speaker":"灵魂叙事","text":"还是沉默。你开始理解墙那边的安静了——它不是空的。它在呼吸。墙那边传来一声轻轻的响动，不是叹气，比叹气更轻、更短。是某种确认。像一个侦探在档案上画了一个圈。她证实了一个她不太喜欢的猜想。现在她知道了，而你还没从她嘴里听到结论，但你已经从沉默里听到了。","next":"ansel_questions_verdict","choices":[]},
      {"id":"ansel_questions_verdict","speaker":"Ansel","text":"「……这不对劲。你不是在装。你是真的什么都没有。」","next":"ansel_talk_hub","choices":[]},
      {"id":"ansel_talk_hub","speaker":"Ansel","text":"「在我去找副列车长之前——你还有什么想问的吗？虽然我也不确定我能回答多少。」","choices":[{"text":"「这列火车……它安全吗？」","next":"hub_train_safe","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":true},{"text":"「你说你是K城的人——那里是什么样的？」","next":"hub_kcity","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":true},{"text":"「墙那边的走廊，是什么样子的？」","next":"hub_corridor","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":true},{"text":"[逻辑推导 中等:9] 仔细听Ansel的声音——她是不是在隐瞒什么？","next":null,"check":{"stat":"逻辑推导","difficulty":9},"success":"hub_ansel_doubt_ok","failure":"hub_ansel_doubt_fail","effects":null,"inputName":false,"loop":true},{"text":"「没事了，去找副列车长吧。」","next":"ansel_goes_for_ezra","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"hub_train_safe","speaker":"Ansel","text":"「安全？这是诺斯塔吉亚号的第一次正式运行。第一条跨空海铁轨。说实话，没人能在这条线上给你保证'安全'两个字怎么写。」","next":"hub_train_safe_knock","choices":[]},
      {"id":"hub_train_safe_knock","speaker":"旁白","text":"她敲了敲墙壁。","next":"hub_train_safe_extra","choices":[]},
      {"id":"hub_train_safe_extra","speaker":"Ansel","text":"「虽然说实话，你这节车厢不在任何结构图上……这让我有点不确定'安全'两个字该怎么写。」","next":"&return","choices":[]},
      {"id":"hub_kcity","speaker":"Ansel","text":"「K城——怎么说呢。空海之后仅剩的两座城市之一。不大。旧城区的楼都不高，外墙是八十年代的白色瓷砖，阴天的时候看起来像一块巨大的肥皂。」","next":"hub_kcity_beat","choices":[]},
      {"id":"hub_kcity_beat","speaker":"旁白","text":"她停了一下。","next":"hub_kcity_pity","choices":[]},
      {"id":"hub_kcity_pity","speaker":"Ansel","text":"「你连K城都不记得了？……算了。当我没问。」","next":"&return","choices":[]},
      {"id":"hub_corridor","speaker":"Ansel","text":"「就是普通的列车走廊。窄。灯光是黄的。墙上有铆钉，地上铺着那种被踩了太多次的地毯——灰绿色的，或者曾经是灰绿色的。」","next":"hub_corridor_beat","choices":[]},
      {"id":"hub_corridor_beat","speaker":"旁白","text":"她顿了顿。","next":"hub_corridor_door","choices":[]},
      {"id":"hub_corridor_door","speaker":"Ansel","text":"「跟你那边差不多，只不过我这边有门。你真的没有门？一扇都没有？」","next":"&return","choices":[]},
      {"id":"hub_ansel_doubt_ok","speaker":"逻辑推导","text":"你说完这句话之后，Ansel沉默了一瞬——比正常的停顿短了大概半秒。\n\n她的声音里有某种东西。不是撒谎——撒谎的人会用更多词。她用的是更少的词。她在省略什么。\n\n也许不是她不想告诉你。也许是你这节没有门的车厢，让\"全部真相\"这个词变得不太适用。","next":"&return","choices":[]},
      {"id":"hub_ansel_doubt_fail","speaker":"逻辑推导","text":"你试图从她的声调、节奏、换气的间隙里提取信息。但隔着这堵墙，声音就像蒙了一层布。你什么都抓不住。\n\n也许她确实在隐瞒什么。也许没有。你无法判断。","next":"&return","choices":[]},
      {"id":"ansel_goes_for_ezra","speaker":"Ansel","text":"「你等着。我去找副列车长。他姓——算了这不重要。他在铁路上干了很多年，他知道的事比我多。」","next":"ansel_goes_beat","choices":[]},
      {"id":"ansel_goes_beat","speaker":"旁白","text":"她顿了顿。","next":"ansel_goes_warn","choices":[]},
      {"id":"ansel_goes_warn","speaker":"Ansel","text":"「别乱动。也别——别敲墙。墙很厚，你敲了也没人听得见。我很快就回来。」","next":"ansel_goes_footsteps","choices":[]},
      {"id":"ansel_goes_footsteps","speaker":"技术专家","text":"脚步声——频率约每分钟一百二十步，步幅偏短，重心落在前脚掌。Ansel的步态说明两件事：她习惯在移动的列车上走路，而且她现在急着去找人。脚步声很快被走廊尽头的嗡鸣吞没了。在隔音如此差的车厢里，你能追踪一个人从站定到完全消失的精确时长：大约十二秒。","next":"waiting_moment","choices":[]},
      {"id":"waiting_moment","speaker":"旁白","text":"Ansel的脚步声沿着走廊远去。\n\n车厢重新安静下来。不，不是安静——是只剩下那种低沉的嗡鸣。窗外的灰雾缓慢地翻涌着，像某种在睡眠中呼吸的巨大生物。\n\n你一个人。\n\n你有一个名字。但没有记忆。没有门。没有——任何东西。\n\n桌上有一片白色药片。你没注意它是从哪儿来的。也许一直在那里。\n\n它散发着一种淡淡的、干净的苦味。","choices":[{"text":"拿起白色药片查看。","next":"examine_pill","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"[缪斯女神 中等:9] 这颗药片让你想起了一首诗——你确定你读过。","next":null,"check":{"stat":"缪斯女神","difficulty":9},"success":"pill_poem","failure":"pill_blank","effects":null,"inputName":false,"loop":false},{"text":"不吃。继续等。","next":"ezra_arrives","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"examine_pill","speaker":"旁白","text":"一片普通的白色药片。比阿司匹林大一点，比安眠药小一点。\n\n标签纸有一半被撕掉了，剩下几个模糊的字迹：\"……安……\"\n\n反面还有一行钢笔写的字，小得几乎看不清：\"不够的话来找我。\"\n\n你不知道这是什么药。但你的手指把它翻来覆去的样子——很熟练。你吃过这种药。或者给什么人吃过。","choices":[{"text":"服用白色药片。","next":"take_pill","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"把药片收起来。","next":"save_pill","check":null,"success":null,"failure":null,"effects":{"add_item":"white_pill"},"inputName":false,"loop":false}]},
      {"id":"pill_poem","speaker":"缪斯女神","text":"白色。圆形的白。\n\n它让你想起——\n\n\"我有一枚白色的药片/在衣兜里放了一整个春天/它慢慢溶化/变成我的指纹/每次我想起自己是谁/就舔一舔手指/——然后忘记。\"\n\n你确定你读过这首诗。一个年轻的女诗人写的。你甚至记得——封面上有一个手绘的窗台。\n\n但你记不起那个诗人的名字了。","next":"examine_pill","choices":[]},
      {"id":"pill_blank","speaker":"缪斯女神","text":"一片药。什么都不是。只是一片药。\n\n你的缪斯好像不在家。","next":"examine_pill","choices":[]},
      {"id":"take_pill","speaker":"旁白","text":"你把药片放进嘴里。没有水，干咽下去的时候喉咙发紧。\n\n几秒后——不是晕眩，是清醒。像是有人把调焦环拧了一下。你脑子里的雾淡了一层。\n\n这东西有用。","next":"ezra_arrives","choices":[],"effects":{"sanity_change":1}},
      {"id":"save_pill","speaker":"旁白","text":"你把药片放进衣兜里。\n\n也许会有更需要它的时候。","next":"ezra_arrives","choices":[]},
      {"id":"ezra_arrives","speaker":"旁白","text":"脚步声——两个人的。一个轻、快，一个沉稳、有节奏。","next":"ezra_arrives_ansel","choices":[]},
      {"id":"ezra_arrives_ansel","speaker":"Ansel","text":"「就是这里。」","next":"ezra_arrives_ezra_intro","choices":[]},
      {"id":"ezra_arrives_ezra_intro","speaker":"旁白","text":"然后是另一个声音。男的。中年。低沉但是不沉重。像是把很多话在肚子里过了一遍才放出来。","next":"ezra_arrives_ezra","choices":[]},
      {"id":"ezra_arrives_ezra","speaker":"Ezra","text":"「你好。我是Ezra，本次列车的副列车长。Ansel跟我说了你的情况。」","next":"ezra_arrives_pause","choices":[]},
      {"id":"ezra_arrives_pause","speaker":"旁白","text":"他停顿了一下。","next":"ezra_arrives_questions","choices":[]},
      {"id":"ezra_arrives_questions","speaker":"Ezra","text":"「我先问你几个问题。姓名？」","next":"ezra_dont_know","choices":[]},
      {"id":"ezra_dont_know","speaker":"旁白","text":"你不知道。","next":"ezra_arrives_age","choices":[]},
      {"id":"ezra_arrives_age","speaker":"Ezra","text":"「年龄？」","next":"ezra_dont_know2","choices":[]},
      {"id":"ezra_dont_know2","speaker":"旁白","text":"你不知道。","next":"ezra_arrives_where","choices":[]},
      {"id":"ezra_arrives_where","speaker":"Ezra","text":"「从哪里上车？」","next":"ezra_dont_know3","choices":[]},
      {"id":"ezra_dont_know3","speaker":"旁白","text":"你不知道。\n\nEzra沉默了一阵。你听到他深吸了一口气。","next":"ezra_arrives_verdict","choices":[]},
      {"id":"ezra_arrives_verdict","speaker":"Ezra","text":"「你说你在一节没有门的车厢里。墙的另一侧是走廊——我的走廊。我在空海边缘跑了二十年的车——补给线、救援线——各种各样的铁轨都跑过。但这列火车，这条跨空海铁轨……是新的。全新的。结构图上从来没有你这节车厢。」","next":"ezra_arrives_tone","choices":[]},
      {"id":"ezra_arrives_tone","speaker":"灵魂叙事","text":"他的语气很平。不是指责，不是审问。他说话的方式像一个已经见过太多怪事的人——怪事本身不让他惊讶，他惊讶的是自己居然还没学会习惯。这种语气里有一种疲惫的诚实。你可以信任一个用这种语气说话的人。","next":"ezra_arrives_not_exist","choices":[]},
      {"id":"ezra_arrives_not_exist","speaker":"Ezra","text":"「你不存在于这列火车上。」","choices":[{"text":"「我知道这听起来不可能。但我在这里。」","next":"ezra_interrogation","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"[逻辑推导 中等:9] Ezra的逻辑是严密的——但他的声音不太对。","next":null,"check":{"stat":"逻辑推导","difficulty":9},"success":"ezra_logic_success","failure":"ezra_interrogation","effects":null,"inputName":false,"loop":false}]},
      {"id":"ezra_interrogation","speaker":"Ezra","text":"「我理解。」","next":"ezra_interrogation_beat","choices":[]},
      {"id":"ezra_interrogation_beat","speaker":"旁白","text":"他的声音慢了下来。","next":"ezra_interrogation_continue","choices":[]},
      {"id":"ezra_interrogation_continue","speaker":"Ezra","text":"「我理解你说的是实话——至少你觉得是。」","next":"ezra_interrogation_move","choices":[]},
      {"id":"ezra_interrogation_move","speaker":"身强体壮","text":"你听到他靠近墙壁。衣料摩擦金属表面——棉布和铆钉，发出一种干燥的、沙沙的声响。他把一只手撑在了墙上。不是拳头，是手掌。你的皮肤甚至能感觉到那个位置传来的微弱震动。他想离你近一点。物理上的近。一个老铁路人的习惯——靠近问题才能判断它有多重。","next":"ezra_interrogation_duty","choices":[]},
      {"id":"ezra_interrogation_duty","speaker":"Ezra","text":"「但你需要理解我的立场。我是一列火车上的副列车长。我的职责是确保车上的每一个人——以及每一项存在——不构成威胁。而你——请别介意——你不存在于任何乘客名单上。你不存在于任何结构图上。你不存在于任何我能查到的记录里。」","next":"ezra_interrogation_ansel","choices":[]},
      {"id":"ezra_interrogation_ansel","speaker":"Ansel","text":"「但他确实在说话。他不是鬼，Ezra。」","next":"ezra_interrogation_ezra","choices":[]},
      {"id":"ezra_interrogation_ezra","speaker":"Ezra","text":"「我知道。这就是问题。鬼倒好办了。」","next":"ezra_relents","choices":[]},
      {"id":"ezra_logic_success","speaker":"逻辑推导","text":"等一下。\n\nEzra说这些话的时候——\"你不存在于这列火车上\"——他的语气不是质疑。不是审问。\n\n是辩护。他是在为一个他自己也无法相信的事实辩护。\n\n你察觉到了。他不是在对你说这些话。他是在说服他自己。\n\n而这个发现比他的审问更让你不安。因为这意味着——他遇到过类似的事。","next":"ezra_relents","choices":[]},
      {"id":"ezra_relents","speaker":"身强体壮","text":"长出一口气。你能听到气流从鼻腔和嘴唇之间挤过的声音——不是叹气，是释放。一个人的横膈膜在做了一个漫长的决定之后终于松开了。这口气里有二十年的铁轨、空海边缘的风、以及一个他以为自己不会再听到的声音。","next":"ezra_relents_voice","choices":[]},
      {"id":"ezra_relents_voice","speaker":"Ezra","text":"「你的声音——我听过。」","next":"ezra_relents_beat","choices":[]},
      {"id":"ezra_relents_beat","speaker":"缪斯女神","text":"这句话像一颗石头掉进水里。不是砸进去的，是松手让它沉下去的。Ezra等了很久才说这句话——你能从水面上的涟漪看出来。它荡开的不是水花，是时间。水面之下，那个二楼窗户里的年轻人，那些夏天的老歌，那棵银杏树——都在波纹里慢慢显形。","next":"ezra_relents_memory","choices":[]},
      {"id":"ezra_relents_memory","speaker":"Ezra","text":"「不是最近。是以前。A城。旧城区。东风路那栋公寓。夏天的晚上，窗户都开着，因为热。我每天收工回家都会听到二楼有人在放音乐。老歌。翻来覆去就那几首。」","next":"ezra_relents_slow","choices":[]},
      {"id":"ezra_relents_slow","speaker":"旁白","text":"他的声音慢了下来。","next":"ezra_relents_confess","choices":[]},
      {"id":"ezra_relents_confess","speaker":"Ezra","text":"「我从来没有见过那个人。但我记得那个声音。过了这么多年——我还是记得。」","next":"ezra_relents_knock","choices":[]},
      {"id":"ezra_relents_knock","speaker":"旁白","text":"他的手指在墙上轻轻叩了一下。","next":"ezra_relents_match","choices":[]},
      {"id":"ezra_relents_match","speaker":"Ezra","text":"「你的声音和他一模一样。」","choices":[{"text":"「那栋公寓楼——说下去。」","next":"ezra_apartment","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"「然后呢？」","next":"ezra_apartment","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"[灵魂叙事 中等:9] 仔细听Ezra的回忆——他形容的不像一个陌生人。","next":null,"check":{"stat":"灵魂叙事","difficulty":9},"success":"ezra_feel_success","failure":"ezra_apartment","effects":null,"inputName":false,"loop":false}]},
      {"id":"ezra_feel_success","speaker":"灵魂叙事","text":"Ezra形容的不是一个陌生人。\n\n那是每天收工回家都能听到的声音。是他生活中固定的一部分——那个二楼的窗户，那些老歌，那个他从来没见过的年轻人。\n\n他不知道为什么这个声音对他很重要。但你知道。你听出来了。\n\n他需要那个声音继续存在。\n\n因为在这个一切都在被空海吞噬的世界里，有一些东西——哪怕只是一个从来没见过的年轻人的声音——必须留下来。","next":"ezra_apartment","choices":[]},
      {"id":"ezra_apartment","speaker":"Ezra","text":"「A城。旧城区。东风路——不对，空海之后改名了，现在叫——算了这不重要。」","next":"ezra_apartment_fast","choices":[]},
      {"id":"ezra_apartment_fast","speaker":"逻辑推导","text":"他说话的速度突然加快了。从之前的平缓节奏跳到了某种更急促的频率——句与句之间的间隔消失了。这不是正常的回忆，这是在翻箱倒柜。Ezra的脑子里有一个储物间，他正在把积压多年的细节一件一件扔出来，因为他怕漏掉什么重要的。人在回忆一个从未谋面的人时，语速和回忆老友时完全不同——前者更快，因为记忆太少了，怕说不完就没了。","next":"ezra_apartment_detail","choices":[]},
      {"id":"ezra_apartment_detail","speaker":"Ezra","text":"「那栋公寓楼不大。六层。没有电梯。外墙是那种八十年代的白色瓷砖，阴天的时候看起来像一块巨大的肥皂。水压不好，四楼以上夏天经常停水。门口有一棵银杏树，秋天的时候——」","next":"ezra_apartment_stop","choices":[]},
      {"id":"ezra_apartment_stop","speaker":"灵魂叙事","text":"他突然停住了。话还没落就断了——不是句号，是破折号后面空白的那种断。他说得太投入了，忘了他面对的是一个不存在于任何名册上的人。这种戛然而止比任何句子都诚实：他不是在回忆一栋楼，他是在回忆一段生活。一段他从来没有理由对任何人说起的生活。","next":"ezra_apartment_awkward","choices":[]},
      {"id":"ezra_apartment_awkward","speaker":"Ezra","text":"「……我在跟你说这些干什么。你又不一定来自那栋楼。」","choices":[{"text":"「说下去。那棵银杏树——」","next":"ezra_ginkgo","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"「503。」","next":"utter_503","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"ezra_ginkgo","speaker":"旁白","text":"你说完这句话之后，Ezra沉默了整整五秒。\n\n不是因为你说错了什么。是——你也不知道自己为什么能看到那棵树。但你看到了。就在你说出来的那个瞬间，你的脑子里浮现了一幅画面：\n\n一棵银杏树。秋天的傍晚。金黄色的扇形叶子铺了一地。树下有个人站着，仰着头往楼上看。\n\n你看不清那个人的脸。\n\n但你在楼上。你在窗户里头。你在往下看。","next":"utter_503","choices":[]},
      {"id":"utter_503","speaker":"你","text":"「503。」","next":"utter_503_beat","choices":[]},
      {"id":"utter_503_beat","speaker":"旁白","text":"你说出这三个数字的时候，声音很轻。轻得几乎像叹一口气。\n\n但墙那边突然没了声音。","next":"utter_503_ansel","choices":[]},
      {"id":"utter_503_ansel","speaker":"Ansel","text":"「什么？你说什么？」","next":"utter_503_ezra","choices":[]},
      {"id":"utter_503_ezra","speaker":"旁白","text":"然后是Ezra。他的语调完全变了——变得警觉。不是害怕。是警觉。","next":"utter_503_ezra_voice","choices":[]},
      {"id":"utter_503_ezra_voice","speaker":"Ezra","text":"「——你刚才说什么？」","choices":[{"text":"「503。我知道这个数字。」","next":"ezra_reacts_to_503","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false},{"text":"「没什么。就是脑子里冒出来的。」","next":"ezra_reacts_to_503","check":null,"success":null,"failure":null,"effects":null,"inputName":false,"loop":false}]},
      {"id":"ezra_reacts_to_503","speaker":"身强体壮","text":"长久的沉默。然后你听到Ezra后退了一步——鞋底和金属地板之间短暂的摩擦声，接着是脚跟在另一块板上落定的闷响。不是随意的一步。是一个人听到了某个不该存在的数字之后，本能地往后让开。他的身体比他的脑子更快地理解了\"503\"意味着什么。","next":"ezra_reacts_ezra","choices":[]},
      {"id":"ezra_reacts_ezra","speaker":"Ezra","text":"「Ansel。你在这里等着。我去叫两个人。」","next":"ezra_reacts_ansel","choices":[]},
      {"id":"ezra_reacts_ansel","speaker":"Ansel","text":"「叫谁？」","next":"ezra_reacts_ezra2","choices":[]},
      {"id":"ezra_reacts_ezra2","speaker":"Ezra","text":"「老列车长——Conrad。还有——」","next":"ezra_reacts_ezra_pause","choices":[]},
      {"id":"ezra_reacts_ezra_pause","speaker":"哲学思辨","text":"他停了一瞬。那一瞬里有东西——还没说出来的东西。","next":"ezra_reacts_ezra_mystery","choices":[]},
      {"id":"ezra_reacts_ezra_mystery","speaker":"Ezra","text":"「还有一个乘客。一位女士。她——你见了就知道了。」","next":"ezra_reacts_ansel2","choices":[]},
      {"id":"ezra_reacts_ansel2","speaker":"Ansel","text":"「她和这事有什么关系？」","next":"ezra_reacts_ezra_leave","choices":[]},
      {"id":"ezra_reacts_ezra_leave","speaker":"旁白","text":"Ezra没有回答。他的脚步声已经走出了好几步。","next":"ezra_reacts_ansel_last","choices":[]},
      {"id":"ezra_reacts_ansel_last","speaker":"Ansel","text":"「{playerName}——你到底是谁？」","next":"first_flash","choices":[]},
      {"id":"first_flash","speaker":"旁白","text":"你没有机会回答。\n\n因为在等待的寂静中，突然——不是画面，不是声音。是**触感**。\n\n你的手指上——湿的。温热的。粘稠的。\n\n你低头看自己的手。干净的。什么都没有。\n\n但那感觉不肯退。它贴在你的指腹上，像是浸透了皮肤。你把手翻过来——掌纹。生命线。干干净净。\n\n然后一个声音碎片——短到几乎不存在——女人的声音。在笑。然后不笑了。\n\n太短了。抓不住。\n\n但你的心跳快了半拍。","next":"train_shakes","choices":[]},
      {"id":"train_shakes","speaker":"旁白","text":"你没有时间思考那个触感意味着什么。\n\n因为就在下一秒——\n\n整列火车猛地一震。\n\n不是刹车。不是转弯。是从轨道深处涌上来的一股力量——像是有什么巨大的东西从地底推了铁轨一把。\n\n车厢里的灯疯狂地晃了两下。桌上的东西滑到了地上。\n\n你试图抓住什么东西——墙、沙发、桌子——手指在金属上滑了一下——\n\n后脑勺撞到了桌椅的边缘。\n\n一声闷响。","next":"train_shakes_ansel","choices":[]},
      {"id":"train_shakes_ansel","speaker":"Ansel","text":"「{playerName}！{playerName}！」","next":"train_shakes_fade","choices":[]},
      {"id":"train_shakes_fade","speaker":"旁白","text":"她的声音很远——像是在一个长长的走廊那头。\n\n世界在往后退。\n\n你的意识变成了一条狭长的缝。在缝隙合拢之前，你看到了最后一幅画面——\n\n一棵银杏树。秋天的傍晚。满地金黄的叶子。\n\n树下有一个人。\n\n这次你看清了他的脸。\n\n那是一个穿深色外套的年轻人——很瘦。他在仰头看二楼的窗户。窗户开着。窗帘被风吹起来。\n\n你认出了他。\n\n不——你认出了那个窗户里的视角。\n\n那是你自己。从窗户里往下看。看着树下的人。\n\n缝隙合拢。\n\n一切归于黑暗。","next":"demo_end","choices":[]},
      {"id":"demo_end","speaker":"旁白","text":"你浮在黑暗里。\n\n但黑暗不是终点——它只是一扇尚未打开的门。\n\n那些碎片——503号房间、银杏树、手指上血的触感、一个女人在笑然后不笑的声音——它们悬浮在黑暗中，像未拆的信。\n\nAnsel还在墙那边吗？Ezra去找谁了？那个老列车长叫什么名字？那个等着儿子回家的女人——她还不知道她等的人已经不在了。\n\n你也不知道。你只知道你在这里。在一节不存在的车厢里。在空海的正中央。\n\n而你还没有死。\n\n**—— 第一章 Demo 完 ——**\n\n感谢试玩。","next":null,"choices":[]}
    ]
  }
}
};
