// ============================================================
// 剧本转换脚本 — Markdown → JavaScript
// 用法: node 剧本/build.js
// 读取 剧本/script_zh.md → 生成 ../script_zh.js
// 读取 剧本/script_en.md → 生成 ../script_en.js
// ============================================================

const fs = require("fs");
const path = require("path");

// 难度数值由 MD 剧本中 [技能 标签:N] 的 N 直接指定，无硬编码映射

// ========== 固定数据模板 ==========

const HEADER_ZH = `// 中文剧本 — 由 build.js 自动生成，请勿手动编辑
// 编辑 剧本/script_zh.md 后运行 node 剧本/build.js 重新生成
window.SCRIPT_ZH = {
  meta: {
    title: "厢间人",
    subtitle: "—— 献给所有困在车厢里的人",
    author: "",
    version: "0.1"
  },
  player: {
    stats: {
      哲学思辨: 3,
      逻辑推导: 4,
      缪斯女神: 2,
      灵魂叙事: 5,
      技术专家: 1,
      身强体壮: 2
    },
    hp: { current: 3, max: 3 },
    sanity: { current: 2, max: 3 }
  },
  itemTemplates: __ITEMS__,
  scenes: __SCENES__
};
`;

const HEADER_EN = `// English script — auto-generated by build.js, DO NOT edit manually
// Edit 剧本/script_en.md then run node 剧本/build.js to regenerate
window.SCRIPT_EN = {
  meta: {
    title: "The Man in Between",
    subtitle: "— For everyone trapped in a carriage",
    author: "",
    version: "0.1"
  },
  player: {
    stats: {
      "Philosophical Thought": 3,
      "Logical Deduction": 4,
      "The Muse": 2,
      "Soul Narrative": 5,
      "Technical Expert": 1,
      "Physical Might": 2
    },
    hp: { current: 3, max: 3 },
    sanity: { current: 2, max: 3 }
  },
  itemTemplates: __ITEMS__,
  scenes: __SCENES__
};
`;

// ========== 解析器 ==========

function parseItemBlock(lines, startIndex) {
  var item = { usable: false, consumeOnUse: false, effect: null };
  var i = startIndex + 1;
  while (i < lines.length) {
    var trimmed = lines[i].trim();
    if (trimmed === "@enditem") {
      return { item: item, endLine: i };
    }
    var colonIdx = trimmed.indexOf(":");
    if (colonIdx >= 0) {
      var key = trimmed.substring(0, colonIdx).trim();
      var value = trimmed.substring(colonIdx + 1).trim();
      if (key === "name") item.name = value;
      else if (key === "desc") item.description = value;
      else if (key === "usable") item.usable = value === "true";
      else if (key === "consume") item.consumeOnUse = value === "true";
      else if (key === "effect") {
        var effectParts = value.split(/\s+/);
        item.effect = {};
        if (effectParts[0] === "sanity_restore") item.effect.sanity_restore = parseInt(effectParts[1]) || 0;
        else if (effectParts[0] === "hp_restore") item.effect.hp_restore = parseInt(effectParts[1]) || 0;
      }
      else if (key === "bullets") item.bullets = parseInt(value) || 0;
    }
    i++;
  }
  return null;
}

function parseMarkdown(md) {
  var items = {};
  var scenes = {};
  var currentScene = null;
  var currentNodes = [];
  var currentNode = null;
  var currentTextLines = [];
  var parsingText = false;

  var lines = md.split(/\r?\n/);

  function flushNode() {
    if (!currentNode || !currentScene) return;
    if (currentTextLines.length > 0) {
      currentNode.text = currentTextLines.join("\n").trim();
    }
    currentNodes.push(currentNode);
    currentNode = null;
    currentTextLines = [];
    parsingText = false;
  }

  function endOfNodeMarker(line) {
    var trimmed = line.trim();
    if (!trimmed) return false;
    return trimmed === "---" ||
           trimmed.startsWith("## ") ||
           trimmed.startsWith("# ") ||
           trimmed.startsWith("→ ") ||
           trimmed.startsWith("? ") ||
           trimmed === "@end";
  }

  var pendingBg = null;
  var pendingMusic = null;
  var pendingVolume = null;
  var inSceneHeader = false; // true = 还在场景头部，@bg/@music 属于场景级

  for (var i = 0; i < lines.length; i++) {
    var raw = lines[i];
    var trimmed = raw.trim();

    // 空行
    if (!trimmed) {
      if (parsingText) currentTextLines.push("");
      continue;
    }

    // 物品模板 @item id ... @enditem
    if (trimmed.startsWith("@item ")) {
      flushNode();
      if (currentScene && currentNodes.length > 0) {
        scenes[currentScene] = scenes[currentScene] || { background: "", music: "", dialogue: [] };
        scenes[currentScene].dialogue = currentNodes;
      }
      currentScene = null;
      currentNodes = [];
      currentNode = null;
      currentTextLines = [];
      parsingText = false;
      var itemId = trimmed.substring(6).trim();
      var result = parseItemBlock(lines, i);
      if (result) {
        result.item.id = itemId;
        items[itemId] = result.item;
        i = result.endLine;
      }
      continue;
    }

    // 场景标题 # 场景名
    if (trimmed.startsWith("# ") && !trimmed.startsWith("## ")) {
      flushNode();
      if (currentScene && currentNodes.length > 0) {
        scenes[currentScene] = scenes[currentScene] || { background: "", music: "", dialogue: [] };
        scenes[currentScene].dialogue = currentNodes;
      }
      currentScene = trimmed.substring(2).trim();
      currentNodes = [];
      currentNode = null;
      currentTextLines = [];
      parsingText = false;
      inSceneHeader = true;
      pendingBg = null;
      pendingMusic = null;
      continue;
    }

    // 场景属性 @bg: @music: @volume:
    // 场景头部（第一个 ## 节点之前）→ 同时存入场景和 pending
    // 节点之间 → 只存 pending，传给下一个节点，不影响场景级
    if (trimmed.startsWith("@bg:") || trimmed.startsWith("@music:") || trimmed.startsWith("@volume:")) {
      if (trimmed.startsWith("@bg:")) {
        var val = trimmed.substring(4).trim();
        if (currentScene) {
          scenes[currentScene] = scenes[currentScene] || { background: "", music: "", dialogue: [] };
          if (inSceneHeader) scenes[currentScene].background = val;
        }
        pendingBg = val;
      } else if (trimmed.startsWith("@music:")) {
        var val = trimmed.substring(7).trim();
        if (currentScene) {
          scenes[currentScene] = scenes[currentScene] || { background: "", music: "", dialogue: [] };
          if (inSceneHeader) scenes[currentScene].music = val;
        }
        pendingMusic = val;
      } else if (trimmed.startsWith("@volume:")) {
        pendingVolume = parseFloat(trimmed.substring(8).trim());
      }
      continue;
    }

    // 节点标题 ## node_id
    if (trimmed.startsWith("## ") && !trimmed.startsWith("### ")) {
      flushNode();
      inSceneHeader = false;
      currentNode = { id: trimmed.substring(3).trim(), speaker: "", text: "", next: undefined, choices: [], bg: undefined, music: undefined, volume: undefined };
      if (pendingBg !== null) { currentNode.bg = pendingBg; pendingBg = null; }
      if (pendingMusic !== null) { currentNode.music = pendingMusic; pendingMusic = null; }
      if (pendingVolume !== null) { currentNode.volume = pendingVolume; pendingVolume = null; }
      parsingText = true;
      continue;
    }

    // 说话人 ### speaker
    if (trimmed.startsWith("### ")) {
      if (currentNode) {
        currentNode.speaker = trimmed.substring(4).trim();
      }
      parsingText = true;
      continue;
    }

    // @end
    if (trimmed === "@end") {
      if (currentNode) {
        currentNode.next = null;
      }
      continue;
    }

    // 自动推进 → next_id
    if (trimmed.startsWith("→ ")) {
      if (currentNode) {
        var rest = trimmed.substring(2).trim();
        var parts = rest.split(/\s+/);
        currentNode.next = parts[0];
        applyEffectsFromParts(currentNode, parts.slice(1));
      }
      continue;
    }

    // 选项 ? ...
    if (trimmed.startsWith("? ")) {
      if (currentNode) {
        var choice = parseChoice(trimmed.substring(2).trim());
        if (choice) {
          currentNode.choices.push(choice);
        }
      }
      continue;
    }

    // 分隔符 ---
    if (trimmed === "---") {
      flushNode();
      continue;
    }

    // 普通文本行
    if (currentNode && parsingText) {
      // 检查是否看起来像一个命令（不应该在这里出现）
      if (endOfNodeMarker(trimmed)) {
        flushNode();
        i--; // re-process this line
        continue;
      }
      currentTextLines.push(trimmed);
    }
  }

  // 最后收尾
  flushNode();
  if (currentScene && currentNodes.length > 0) {
    scenes[currentScene] = scenes[currentScene] || { background: "", music: "", dialogue: [] };
    scenes[currentScene].dialogue = currentNodes;
  }

  return { items: items, scenes: scenes };
}

function parseChoice(text) {
  // 格式1: 选项文字 → next_id [&loop] @effects
  // 格式2: [技能 难度:N] 选项文字 → 成功:success_id | 失败:fail_id @effects
  var choice = { text: "", next: null, check: null, success: null, failure: null, effects: null, inputName: false, loop: false };

  // 提取效果标记
  var effectStart = text.indexOf(" @");
  var effectStr = "";
  if (effectStart >= 0) {
    effectStr = text.substring(effectStart + 1).trim();
    text = text.substring(0, effectStart).trim();
  }

  // 检查是否是技能检定
  var checkMatch = text.match(/^\[(.+?)\s+(简单|中等|困难|Simple|Easy|Medium|Hard):(\d+)\]\s*(.+)/);
  if (checkMatch) {
    var statName = checkMatch[1].trim();
    var diffLabel = checkMatch[2];
    var diffValue = parseInt(checkMatch[3]);
    var restText = checkMatch[4].trim();

    choice.check = { stat: statName, difficulty: diffValue };
    choice.text = "[" + statName + " " + diffLabel + ":" + choice.check.difficulty + "] " + restText;

    // 解析 成功:id | 失败:id
    var branchMatch = restText.match(/→\s*成功:(\S+)\s*\|\s*失败:(\S+)/);
    if (branchMatch) {
      choice.success = branchMatch[1];
      choice.failure = branchMatch[2];
      // 去掉分支信息，保留选项描述文字
      choice.text = "[" + statName + " " + diffLabel + ":" + choice.check.difficulty + "] " +
                    restText.substring(0, restText.indexOf("→")).trim();
      // 检查 &loop 标记
      if (restText.indexOf("&loop") >= 0) choice.loop = true;
    }
  } else {
    // 普通选项: 文字 → next_id [&loop]
    var arrowIdx = text.indexOf("→");
    if (arrowIdx >= 0) {
      choice.text = text.substring(0, arrowIdx).trim();
      var afterArrow = text.substring(arrowIdx + 1).trim();
      var parts = afterArrow.split(/\s+/);
      choice.next = parts[0];
      // 检查 &loop 标记
      var restParts = [];
      for (var pi = 1; pi < parts.length; pi++) {
        if (parts[pi] === "&loop") {
          choice.loop = true;
        } else {
          restParts.push(parts[pi]);
        }
      }
      if (restParts.length > 0) {
        effectStr = restParts.join(" ");
      }
    } else {
      choice.text = text;
    }
  }

  // 解析效果
  if (effectStr) {
    choice.effects = parseEffects(effectStr);
  }

  return choice;
}

function parseEffects(effectStr) {
  var effects = {};
  var parts = effectStr.split(/\s+/);
  for (var i = 0; i < parts.length; i++) {
    var p = parts[i];
    if (p === "@inputName") {
      effects.inputName = true;
    } else if (p.startsWith("@sanity:")) {
      effects.sanity_change = parseInt(p.substring(8));
    } else if (p.startsWith("@hp:")) {
      effects.hp_change = parseInt(p.substring(4));
    } else if (p.startsWith("@addItem:")) {
      effects.add_item = p.substring(9);
    } else if (p.startsWith("@removeItem:")) {
      effects.remove_item = p.substring(12);
    }
  }
  return Object.keys(effects).length > 0 ? effects : null;
}

function applyEffectsFromParts(node, parts) {
  var effectStr = parts.join(" ");
  if (effectStr) {
    var effects = parseEffects(effectStr);
    if (effects) node.effects = effects;
  }
}

// ========== 序列化为 JS ==========

function itemsToJS(items) {
  var keys = Object.keys(items);
  if (keys.length === 0) return "{}";
  var parts = ["{"];
  for (var i = 0; i < keys.length; i++) {
    var key = keys[i];
    parts.push('    ' + JSON.stringify(key) + ': ' + JSON.stringify(items[key]) + (i < keys.length - 1 ? ',' : ''));
  }
  parts.push('  }');
  return parts.join('\n');
}

function scenesToJS(scenes) {
  var parts = ["{"];
  var sceneNames = Object.keys(scenes);
  for (var i = 0; i < sceneNames.length; i++) {
    var name = sceneNames[i];
    var scene = scenes[name];
    parts.push('  ' + JSON.stringify(name) + ': {');
    parts.push('    background: ' + JSON.stringify(scene.background || "") + ',');
    parts.push('    music: ' + JSON.stringify(scene.music || "") + ',');
    parts.push('    dialogue: [');
    var dialogue = scene.dialogue;
    for (var j = 0; j < dialogue.length; j++) {
      var node = dialogue[j];
      parts.push('      ' + JSON.stringify(node) + (j < dialogue.length - 1 ? ',' : ''));
    }
    parts.push('    ]');
    parts.push('  }' + (i < sceneNames.length - 1 ? ',' : ''));
  }
  parts.push('}');
  return parts.join('\n');
}

// ========== 主流程 ==========

function build(lang) {
  var mdFile = path.join(__dirname, "script_" + lang + ".md");
  var outFile = path.join(__dirname, "..", "js", "script_" + lang + ".js");
  var header = lang === "zh" ? HEADER_ZH : HEADER_EN;

  if (!fs.existsSync(mdFile)) {
    console.log("[跳过] " + mdFile + " 不存在");
    return;
  }

  console.log("[读取] " + mdFile);
  var md = fs.readFileSync(mdFile, "utf-8");
  var result = parseMarkdown(md);
  var itemsJS = itemsToJS(result.items);
  var scenesJS = scenesToJS(result.scenes);
  var output = header.replace("__ITEMS__", itemsJS).replace("__SCENES__", scenesJS);
  fs.writeFileSync(outFile, output, "utf-8");
  console.log("[生成] " + outFile + " (共 " + Object.keys(result.items).length + " 个物品, " + Object.keys(result.scenes).length + " 个场景)");
}

build("zh");
build("en");
console.log("[完成] 剧本转换结束");
