// English script — auto-generated by build.js, DO NOT edit manually
// Edit 剧本/script_en.md then run node 剧本/build.js to regenerate
window.SCRIPT_EN = {
  meta: {
    title: "The Man in Between",
    subtitle: "— For everyone trapped in a carriage",
    author: "",
    version: "0.1"
  },
  player: {
    stats: {
      "Philosophical Speculation": 3,
      "Logical Deduction": 4,
      "Muse": 2,
      "Soul Narrative": 5,
      "Technical Expertise": 1,
      "Physical Strength": 2
    },
    hp: { current: 3, max: 3 },
    sanity: { current: 2, max: 3 }
  },
  itemTemplates: {
    "white_pill": {"usable":true,"consumeOnUse":true,"effect":{"sanity_restore":1},"name":"White Pill","description":"A white tablet with a faint grassy smell. The label is half-torn, leaving only a handwritten character: 'An...'","id":"white_pill"},
    "pistol": {"usable":false,"consumeOnUse":false,"effect":null,"name":"Standard-Issue Pistol","description":"A dark, cold service pistol. Found under the sofa. Three rounds left in the magazine.","bullets":3,"id":"pistol"}
  },
  scenes: {
  "Opening": {
    background: "assets/bg_开场.png",
    music: "",
    dialogue: [
      {"id":"wake_up","speaker":"","text":"You are waking up.\n\nNo — more precisely, you are in the process of waking. Consciousness seeps upward like water beneath thin ice, slow and uncertain. You feel yourself floating on some kind of boundary: darkness on one side, a grey-white light on the other.\n\nThe back of your head is pressed against cold metal.","next":"first_look","choices":[]},
      {"id":"first_look","speaker":"Narrator","text":"You open your eyes.\n\nThe ceiling is low. Rivets. Joints between metal plates. A yellow-amber light sways gently overhead with a rhythm — like something underwater.\n\nA low, steady hum. Not tinnitus. It comes from inside the walls.","next":"stand_up","choices":[]},
      {"id":"stand_up","speaker":"Narrator","text":"You try to stand. Your legs are weak — not from exhaustion, but from a more fundamental strangeness, as if these muscles do not belong to you, as if you have not yet settled into whatever relationship you have with this body.\n\nYou brace yourself against the wall. It vibrates.","next":null,"choices":[{"text":"Look around.","next":"look_around","check":null,"success":null,"failure":null,"effects":null,"inputName":false},{"text":"\"Anyone there?\"","next":"call_out","check":null,"success":null,"failure":null,"effects":null,"inputName":false}]}
    ]
  }
}
};
